// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtlCCrmWOnt7g2GTxlovlqIWlo6HV-UUg',
    appId: '1:660259657109:web:b1cff790ae3945eea8129c',
    messagingSenderId: '660259657109',
    projectId: 'yoshua-store',
    authDomain: 'yoshua-store.firebaseapp.com',
    storageBucket: 'yoshua-store.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVnlnkbjzTLKLYXl54kejWlzfTStPIch0',
    appId: '1:660259657109:android:fe1584cea3b856b7a8129c',
    messagingSenderId: '660259657109',
    projectId: 'yoshua-store',
    storageBucket: 'yoshua-store.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAnozGcZTflwhksEXK9zY60ThVD-EGACU',
    appId: '1:660259657109:ios:a24efd6c4f0efabba8129c',
    messagingSenderId: '660259657109',
    projectId: 'yoshua-store',
    storageBucket: 'yoshua-store.appspot.com',
    iosBundleId: 'com.example.yoshuaStore',
  );
}
